import { BLOCK_TYPE, EASING, PROPERTY } from "../types.mjs";

const assetsPrefixUrl =
	"https://statics.dmcdn.net/d/PRODUCTION/2025/POC_CanvasToVideo/assets/asics/";

export const campaignAsics = {
	scene: {
		width: 1920,
		height: 1080,
	},
	blocks: [
		{
			type: BLOCK_TYPE.video,
			name: "video",
			version: "",
			props: {
				src: `${assetsPrefixUrl}video_high.mp4`,
				isMainVideo: true,
				x: 0,
				y: 0,
				width: 1920,
				height: 1080,
				scale: 1,
				opacity: 1,
				zIndex: 0,
				animations: [
					{
						property: PROPERTY.opacity,
						endValue: 1,
						startTime: 400,
						duration: 300,
					},
					{
						property: PROPERTY.scale,
						endValue: 1,
						startTime: 400,
						duration: 1300,
						easing: EASING.bounceOut,
					},
				],
			},
		},
		{
			type: BLOCK_TYPE.image,
			name: "bg",
			version: "",
			props: {
				src: `${assetsPrefixUrl}bg.png`,
				x: 0,
				y: 0,
				width: 1920,
				height: 1080,
				opacity: 1,
				zIndex: 1,
			},
		},

		{
			type: BLOCK_TYPE.image,
			name: "product0",
			version: "",
			props: {
				src: `${assetsPrefixUrl}product0.png`,
				x: 1140,
				y: 30,
				width: 616,
				height: 789,
				opacity: 1,
				zIndex: 2,
				animations: [
					{
						property: PROPERTY.y,
						startValue: 1200,
						endValue: 30,
						startTime: 7000,
						duration: 400,
						repeatDelay: 8000,
						count: Infinity,
						easing: EASING.easeOut,
					},
					{
						property: PROPERTY.y,
						startValue: 30,
						endValue: -1000,
						startTime: 1000,
						duration: 400,
						repeatDelay: 8000,
						count: Infinity,
						easing: EASING.easeOut,
					},
				],
			},
		},
		{
			type: BLOCK_TYPE.image,
			name: "product1",
			version: "",
			props: {
				src: `${assetsPrefixUrl}product1.png`,
				x: 1140,
				y: 1200,
				width: 616,
				height: 789,
				opacity: 1,
				zIndex: 2,
				animations: [
					{
						property: PROPERTY.y,
						startValue: 1200,
						endValue: 30,
						startTime: 1000,
						duration: 400,
						repeatDelay: 8000,
						count: Infinity,
						easing: EASING.easeOut,
					},
					{
						property: PROPERTY.y,
						endValue: -1000,
						startTime: 3000,
						duration: 400,
						repeatDelay: 8000,
						count: Infinity,
						easing: EASING.easeOut,
					},
				],
			},
		},
		{
			type: BLOCK_TYPE.image,
			name: "product2",
			version: "",
			props: {
				src: `${assetsPrefixUrl}product2.png`,
				x: 1140,
				y: 1200,
				width: 616,
				height: 789,
				opacity: 1,
				zIndex: 2,
				animations: [
					{
						property: PROPERTY.y,
						startValue: 1200,
						endValue: 30,
						startTime: 3000,
						duration: 400,
						repeatDelay: 8000,
						count: Infinity,
						easing: EASING.easeOut,
					},
					{
						property: PROPERTY.y,
						endValue: -1000,
						startTime: 5000,
						duration: 400,
						repeatDelay: 8000,
						count: Infinity,
						easing: EASING.easeOut,
					},
				],
			},
		},
		{
			type: BLOCK_TYPE.image,
			name: "product3",
			version: "",
			props: {
				src: `${assetsPrefixUrl}product3.png`,
				x: 1140,
				y: 1200,
				width: 616,
				height: 789,
				opacity: 1,
				zIndex: 2,
				animations: [
					{
						property: PROPERTY.y,
						startValue: 1200,
						endValue: 30,
						startTime: 5000,
						duration: 400,
						repeatDelay: 8000,
						count: Infinity,
						easing: EASING.easeOut,
					},
					{
						property: PROPERTY.y,
						endValue: -1000,
						startTime: 7000,
						duration: 400,
						repeatDelay: 8000,
						count: Infinity,
						easing: EASING.easeOut,
					},
				],
			},
		},
	],
};
